/**
 * This file is more or less useless but I spent so much time making it that it
 * has sentimental value to me now and I'm not gonna delete it.
 */

export const awardTypes:string[] = [
    'Chairman\'s Award',
    'Regional',
    'Regional Finalist',
    'Woodie Flowers Award',
    'Dean\'s List Award',
    'Volunteer Award',
    'Founder\'s Award',
    'Bart Kamen Memorial Award',
    'Make it Loud Award',
    'Engineering Inspiration Award',
    'Rookie All-Star Award',
    'Gracious Professionalism Award',
    'Coopertition Award',
    'Judge\'s Award',
    'Highest Rookie Seed Award',
    'Rookie Inspiration Award',
    'Industrial Design Award',
    'Quality Award',
    'Safety Award',
    'Sportsmanship Award',
    'Creativity Award',
    'Engineering Excellence Award',
    'Entrepreneurship Award',
    'Excellence in Design Award',
    'Excellence in CAD Design Award',
    'Excellence in Animation Design Award',
    'Driving Tomorrow\'s Change Award',
    'Imagery Award',
    'Media and Technology Award',
    'Innovation in Control Award',
    'Spirit Award',
    'Website Award',
    'Visualization Award',
    'Autodesk Inventor Award',
    'Future Innovator Award',
    'Recognition of Extraordinary Service Award',
    'Outstanding Cart Award',
    'WSU Aim Higher Award',
    'Leadership in Control Award',
    'Number One Seed',
    'Incredible Play Award',
    'People\'s Choice Animation Award',
    'Visualization Rising Star Award',
    'Best Offensive Round Award',
    'Best Play of the Day Award',
    'Featherweight in the Finals Award',
    'Most Photogenic Award',
    'Outstanding Defence Award',
    'Power to Simplify Award',
    'Against All Odds Award',
    'Rising Star Award',
    'Chairman\'s Honorable Mention',
    'Content Communication Honorable Mention',
    'Technical Execution Honorable Mention',
    'Realization Award',
    'Realization Honorable Mention',
    'Design Your Future Award',
    'Design Your Future Honorable Mention',
    'Special Recognition Character Animation',
    'High Score',
    'Teacher Pioneer Award',
    'Best Craftmanship Award',
    'Best Defensive Match Award',
    'Play of the Day Award',
    'Programming Award',
    'Professionalism Award',
    'Golden Corndog Award',
    'Most Improved Team Award',
    'Wildcard',
    'Chairman\'s Finalist',
    'Other',
    'Autonomous Award'
]

export const blueBanners = [0, 1, 3, 69]